-- Memory optimized table
CREATE TABLE [dbo].[Table1]
(
	[Id] INT NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT = 131072),
	[c2] nvarchar(30) NOT NULL, 
    INDEX [IX_Table1_Column] NONCLUSTERED HASH (c2) WITH (BUCKET_COUNT = 131072)
) WITH (MEMORY_OPTIMIZED = ON)

GO