//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Public.Dac.Samples.Rules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RuleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RuleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Public.Dac.Samples.Rules.RuleResources", typeof(RuleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITFOR DELAY statement was found in {0}.
        /// </summary>
        internal static string AvoidWaitForDelay_ProblemDescription {
            get {
                return ResourceManager.GetString("AvoidWaitForDelay_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid using WaitFor Delay statements in stored procedures, functions and triggers..
        /// </summary>
        internal static string AvoidWaitForDelay_RuleName {
            get {
                return ResourceManager.GetString("AvoidWaitForDelay_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create ResourceManager for {0} from {1}..
        /// </summary>
        internal static string CannotCreateResourceManager {
            get {
                return ResourceManager.GetString("CannotCreateResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not start with a capital letter. Lowercase names are not recommended.
        /// </summary>
        internal static string CapitalizedNames_ProblemDescription {
            get {
                return ResourceManager.GetString("CapitalizedNames_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All TSQL objects should have a capitalized or uppercase name. Lowercase names are not recommended.
        /// </summary>
        internal static string CapitalizedNames_RuleName {
            get {
                return ResourceManager.GetString("CapitalizedNames_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SamplesCategory.
        /// </summary>
        internal static string CategorySamples {
            get {
                return ResourceManager.GetString("CategorySamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index {0} is on a character column {1} that does not use a *_BIN2 collation. This is not supported for indexes on memory optimized tables. The collation &apos;{2}&apos; for the database or for the specified column should be changed.
        /// </summary>
        internal static string InMemoryBinCollection_ProblemDescription {
            get {
                return ResourceManager.GetString("InMemoryBinCollection_ProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexes on character columns that do not use a *_BIN2 collation are not supported with indexes on memory optimized tables.
        /// </summary>
        internal static string InMemoryBinCollection_RuleName {
            get {
                return ResourceManager.GetString("InMemoryBinCollection_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index {0} on view {1} is not allowed, as the view references a memory optimized table {2}.
        /// </summary>
        internal static string ViewsOnMemoryOptimizedTable_IndexProblemDescription {
            get {
                return ResourceManager.GetString("ViewsOnMemoryOptimizedTable_IndexProblemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views on memory optimized tables should be schema bound.
        /// </summary>
        internal static string ViewsOnMemoryOptimizedTable_RuleName {
            get {
                return ResourceManager.GetString("ViewsOnMemoryOptimizedTable_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} must specify the &apos;WITH SCHEMABINDING&apos; view attribute as it references a memory optimized table {1}.
        /// </summary>
        internal static string ViewsOnMemoryOptimizedTable_SchemaBindingProblemDescription {
            get {
                return ResourceManager.GetString("ViewsOnMemoryOptimizedTable_SchemaBindingProblemDescription", resourceCulture);
            }
        }
    }
}
